# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/corey/mit/6.337/yanni_code/finalproj/DSP/DSP.cache/wt [current_project]
set_property parent.project_path /home/corey/mit/6.337/yanni_code/finalproj/DSP/DSP.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/corey/mit/6.337/yanni_code/finalproj/DSP/DSP.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem /home/corey/mit/6.337/yanni_code/finalproj/DSP/DSP.srcs/sources_1/new/coeff.list
read_verilog -library xil_defaultlib {
  /home/corey/mit/6.337/yanni_code/finalproj/DSP/DSP.srcs/sources_1/imports/new/adau1761_controller.v
  /home/corey/mit/6.337/yanni_code/finalproj/DSP/DSP.srcs/sources_1/new/alt_divider.v
  /home/corey/mit/6.337/yanni_code/finalproj/DSP/DSP.srcs/sources_1/new/clock_sync.v
  /home/corey/mit/6.337/yanni_code/finalproj/DSP/DSP.srcs/sources_1/new/delay_1.v
  /home/corey/mit/6.337/yanni_code/finalproj/DSP/DSP.srcs/sources_1/new/fir_floating.v
  /home/corey/mit/6.337/yanni_code/finalproj/DSP/DSP.srcs/sources_1/new/float_memory.v
  /home/corey/mit/6.337/yanni_code/finalproj/DSP/DSP.srcs/sources_1/new/i2cmaster.v
  /home/corey/mit/6.337/yanni_code/finalproj/DSP/DSP.srcs/sources_1/new/i2s_rx.v
  /home/corey/mit/6.337/yanni_code/finalproj/DSP/DSP.srcs/sources_1/new/i2s_tx.v
  /home/corey/mit/6.337/yanni_code/finalproj/DSP/DSP.srcs/sources_1/imports/new/toplevel.v
}
read_verilog -library float_lib {
  /home/corey/mit/6.337/yanni_code/finalproj/fpu_custom/all/adder.v
  /home/corey/mit/6.337/yanni_code/finalproj/fpu_custom/all/multiplier.v
}
read_ip -quiet /home/corey/mit/6.337/yanni_code/finalproj/DSP/DSP.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/corey/mit/6.337/yanni_code/finalproj/DSP/DSP.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/corey/mit/6.337/yanni_code/finalproj/DSP/DSP.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/corey/mit/6.337/yanni_code/finalproj/DSP/DSP.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property is_locked true [get_files /home/corey/mit/6.337/yanni_code/finalproj/DSP/DSP.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/corey/mit/6.337/yanni_code/finalproj/DSP/DSP.srcs/constrs_1/imports/verilog/NexysVideo_Master.xdc
set_property used_in_implementation false [get_files /home/corey/mit/6.337/yanni_code/finalproj/DSP/DSP.srcs/constrs_1/imports/verilog/NexysVideo_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top toplevel -part xc7a200tsbg484-1


write_checkpoint -force -noxdef toplevel.dcp

catch { report_utilization -file toplevel_utilization_synth.rpt -pb toplevel_utilization_synth.pb }
