# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/yanni/18.335/finalproj/18.335proj/18.335proj.cache/wt [current_project]
set_property parent.project_path /home/yanni/18.335/finalproj/18.335proj/18.335proj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys_video:part0:1.1 [current_project]
add_files -quiet /home/yanni/18.335/finalproj/18.335proj/18.335proj.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files /home/yanni/18.335/finalproj/18.335proj/18.335proj.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
read_verilog -library xil_defaultlib {
  /home/yanni/18.335/finalproj/18.335proj/18.335proj.srcs/sources_1/new/adau1761i2c.v
  /home/yanni/18.335/finalproj/18.335proj/18.335proj.srcs/sources_1/new/divider.v
  /home/yanni/18.335/finalproj/18.335proj/18.335proj.srcs/sources_1/new/adau1761_controller.v
  /home/yanni/18.335/finalproj/18.335proj/18.335proj.srcs/sources_1/new/toplevel.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/yanni/18.335/finalproj/18.335proj/18.335proj.srcs/constrs_1/imports/verilog/NexysVideo_Master.xdc
set_property used_in_implementation false [get_files /home/yanni/18.335/finalproj/18.335proj/18.335proj.srcs/constrs_1/imports/verilog/NexysVideo_Master.xdc]


synth_design -top toplevel -part xc7a200tsbg484-1


write_checkpoint -force -noxdef toplevel.dcp

catch { report_utilization -file toplevel_utilization_synth.rpt -pb toplevel_utilization_synth.pb }
