webtalk_init -webtalk_dir /home/yanni/18.335/finalproj/DSP/simulation/fixed_simulation/xsim/xsim.dir/fir_fixed_file_tb/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun May 14 20:33:31 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1846317" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "94f87975d14b5a14bacf453d441b8afd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3fbe5866-1d04-4a9c-bbf7-73577242020e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1340" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 17.04" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3599.908 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "67.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "118286592 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "606.80_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "128188_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3480283780 -regid "" -xml /home/yanni/18.335/finalproj/DSP/simulation/fixed_simulation/xsim/xsim.dir/fir_fixed_file_tb/webtalk/usage_statistics_ext_xsim.xml -html /home/yanni/18.335/finalproj/DSP/simulation/fixed_simulation/xsim/xsim.dir/fir_fixed_file_tb/webtalk/usage_statistics_ext_xsim.html -wdm /home/yanni/18.335/finalproj/DSP/simulation/fixed_simulation/xsim/xsim.dir/fir_fixed_file_tb/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
