webtalk_init -webtalk_dir /home/corey/mit/6.337/yanni_code/finalproj/DSP/simulation/float_simulation/xsim/xsim.dir/fir_floating_file_tb/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat May 13 20:47:14 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1846317" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6fd6e23d-9673-4e15-b255-5d170cc46734" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "940f8c9b-83b8-4de6-a145-c9c90e01f3ea" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "96" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 14.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3589.394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "236800 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "5.59_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "131260_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1393455264 -regid "" -xml /home/corey/mit/6.337/yanni_code/finalproj/DSP/simulation/float_simulation/xsim/xsim.dir/fir_floating_file_tb/webtalk/usage_statistics_ext_xsim.xml -html /home/corey/mit/6.337/yanni_code/finalproj/DSP/simulation/float_simulation/xsim/xsim.dir/fir_floating_file_tb/webtalk/usage_statistics_ext_xsim.html -wdm /home/corey/mit/6.337/yanni_code/finalproj/DSP/simulation/float_simulation/xsim/xsim.dir/fir_floating_file_tb/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
